os: Visual Studio 2015

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - PYTHON: 'C:/Python27'
    - PYTHON: 'C:/Python27-x64'
    - PYTHON: 'C:/Python34'
    - PYTHON: 'C:/Python34-x64'
    - PYTHON: 'C:/Python35'
    - PYTHON: 'C:/Python35-x64'
    - PYTHON: 'C:/Python36'
    - PYTHON: 'C:/Python36-x64'
    - PYTHON: 'C:/Python37'
    - PYTHON: 'C:/Python37-x64'
      cfscrape_node: '4.5'
    - PYTHON: 'C:/Python37-x64'
      cfscrape_node: 'node'

install:
  - ps: >-
      If ($env:cfscrape_node -ne $null) {
        If ($env:cfscrape_node -Match "node") {
          Install-Product node ""
        }
        Else {
          Install-Product node $env:cfscrape_node
        }
      }
  - 'set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%'
  - 'python --version'
  - 'node -p process.versions'
  - 'pip -V'
  - 'pip install pipenv'
  - 'pipenv install --dev'

# Not a C# project, build stuff at the install step instead.
build: false

test_script: 'pipenv run pytest tests'
